### ISSUE TITLE
Consider modifying visualize_cluster to do the clustering for you. 

### ISSUE THREAD

**Issue by cmaclell** [cmaclell/concept_formation#49]
I'm not sure exactly what this would look like, but it would be nice if we could do something like, visualize_cluster(tree, instances, criterion="BIC") and it would generate the tree for you, without you having to know how do use the clustering stuff.

**Comment by eharpste** [comment]
I was hesitant to do this because there are a bunch of parameters to the clustering functions that would be duplicated, (e.g., criterion, number of splits, and modifying or not). My vote would be to make the documentation for the function clearer and link to the cluster module itself. I'm not sure what it would look like to put a doctest in there or make an example of how to use it given how it generates the html but that might also help.
