### ISSUE TITLE
Regression on a multiple feature dataset

### ISSUE THREAD

**Issue by sunilchandraar** [cmaclell/concept_formation#57]
I have a dataframe with 79 features with mixed data types (X) and one target variable (y) which is a continuous numerical data.
In order to apply TrestleTree regression to predict y value, dataframe X was converted to a 2D numpy array as suggested in http://concept-formation.readthedocs.io/en/latest/examples/regression.html. 
I was able to create training data as in the regression example (documentation) but while fitting the data to the model , ttree.fit(training_data, iterations=1) , I'm getting Type error : 'TrestleTree only works with hashable values. Please suggest how to overcome this error

'

**Comment by cmaclell** [comment]
From your description, it is a bit unclear what format your training data takes. Is it a list of numpy arrays? If so, that definitely won't work because numpy arrays are not hashable. You'll need to convert the arrays into dictionaries. You can do this using a line similar to the example you mention:

```
training_data = [{'x': float(X[i][0]), '_y': float(y[i])} for i, v in enumerate(X)]
```

Hope this helps!

Chris
